import streamlit as st
import requests

BASE_URL = "http://localhost:8000"
st.set_page_config(layout="wide", page_title="POC for Notesight")

st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Home", "Flashcards","Notes"])

if page == "Home":
    st.title("📄 Document Chat using vectors")

    uploaded_file = st.file_uploader("Upload a PDF document", type=["pdf"])

    if uploaded_file:
        files = {"file": (uploaded_file.name, uploaded_file, "application/pdf")}
        response = requests.post(f"{BASE_URL}/upload/", files=files)

        if response.status_code == 200:
            st.success("✅ File uploaded successfully!")
            file_path = response.json().get("file_path")
        else:
            st.error("❌ Failed to upload file")
            st.stop()

    st.subheader("💬 Ask Questions About the Document")

    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    query = st.chat_input("Ask a question about the document...")
    if query:
        with st.chat_message("user"):
            st.markdown(query)
        st.session_state.messages.append({"role": "user", "content": query})

        response = requests.post(f"{BASE_URL}/ask/", data={"query": query})

        answer = response.json().get("answer", "⚠ No response received.") if response.status_code == 200 else "❌ Error: Failed to get a response."

        with st.chat_message("assistant"):
            st.markdown(answer)

        st.session_state.messages.append({"role": "assistant", "content": answer})

elif page == "Notes":
    st.title("📄 Generate AI-Powered Notes")

    uploaded_files = st.file_uploader("Upload PDFs for Notes Generation", type=["pdf"], accept_multiple_files=True)

    if uploaded_files:
        files = [("files", (file.name, file, "application/pdf")) for file in uploaded_files]
        model = st.selectbox("Select AI Model", ["chatgpt", "gemini", "mistral"])

        if st.button("📝 Generate Notes"):
            response = requests.post(f"{BASE_URL}/notes/", files=files, data={"model": model}, stream=True)

            if response.status_code == 200:
                st.subheader("Generated Notes:")

                notes_placeholder = st.empty()
                notes_text = ""
                
                for chunk in response.iter_content(chunk_size=1024):
                    if chunk:
                        decoded_chunk = chunk.decode("utf-8")
                        notes_text += decoded_chunk
                        notes_placeholder.markdown(notes_text)

            else:
                st.error("❌ Failed to generate notes")

elif page == "Flashcards":
    st.title("📚 Flashcard Generator")

    model_options = {"ChatGPT": "chatgpt", "Gemini": "gemini", "Mistral": "mistral"}
    selected_model = st.selectbox("Select AI Model", list(model_options.keys()))

    uploaded_files = st.file_uploader("Upload PDFs for Flashcards", type=["pdf"], accept_multiple_files=True)

    if st.button("🔹 Generate Flashcards"):
        if uploaded_files:
            files = [("files", (file.name, file, "application/pdf")) for file in uploaded_files]
            data = {"model": model_options[selected_model]}

            with st.spinner(f"Generating flashcards using {selected_model}... ⏳"):
                response = requests.post(f"{BASE_URL}/flashcards/", files=files, data=data)

                if response.status_code == 200:
                    flashcards = response.json().get("flashcards", [])

                    if flashcards:
                        st.subheader(f"📝 Flashcards (Generated by {selected_model})")
                        for flashcard in flashcards:
                            with st.expander(f"**{flashcard.get('concept', 'Unknown Concept')}**"):
                                st.write(flashcard.get("definition", "No Definition Provided"))
                    else:
                        st.warning("⚠ No flashcards were generated.")
                else:
                    st.error(f"❌ Failed to generate flashcards using {selected_model}")
        else:
            st.warning("⚠ Please upload at least one file first.")

